import { randomBytes } from "node:crypto";
import { chmod, copyFile, mkdir, open, readFile, readdir, rename, rm, stat, unlink } from "node:fs/promises";
import { dirname, join, basename } from "node:path";
import { projectKey, type ReflectionLayer } from "./config.js";

export type Evidence = "user-correction" | "repeated-process-failure" | "review-artifact-defect" | "retry-policy-violation";
export type EntryStatus = "active" | "promotable" | "promoted";
export interface ReflectionEntry { id: string; scope: string; trigger: string; cause: string; prevention: string; evidence: Evidence; evidenceRef: string; hits: number; firstSeen: string; lastSeen: string; status: EntryStatus; promotedRef?: string; promotedAtVersion?: string }
export interface ReflectionBucket { v: 1; updatedAt: string; entries: ReflectionEntry[] }
export interface ReflectionStoreOptions { now?: () => number; sleep?: (ms: number) => Promise<void>; warn?: (code: string) => void; processAlive?: (pid: number) => boolean }
type HeldLock = { handle: import("node:fs/promises").FileHandle; path: string; token: string; timer: ReturnType<typeof setInterval> };
export class ReflectionError extends Error { constructor(readonly code: string) { super(code); } }
const EMPTY = (): ReflectionBucket => ({ v: 1, updatedAt: new Date(0).toISOString(), entries: [] });
const evidence = new Set<Evidence>(["user-correction", "repeated-process-failure", "review-artifact-defect", "retry-policy-violation"]);
const caps: Record<ReflectionLayer, number> = { run: 12, project: 24, global: 16 };
const ages: Record<ReflectionLayer, number> = { run: 6 * 3600000, project: 30 * 86400000, global: 90 * 86400000 };
const MAX_LEASE_AGE = 60_000;
const MAX_STALE_LOCK_CLEANUP = 256;
const MAX_ENTRY_BYTES = 768;
const activeTokens = new Set<string>();
const prohibited = /[\n\r\t\u0000-\u001f\u007f]|```|(?:api[_ -]?key|password|secret|token)|private\s+key|https?:\/\/|\b(?:PVT[A-Z]{0,4}|DI)_[A-Za-z0-9]+\b|(?:^|\s)[+\-]{3}(?:\s|$)|\b[0-9a-f]{32,}\b|\b[A-Za-z0-9+/]{40,}={0,2}\b/iu;
const jsonBytes = (value: unknown) => Buffer.byteLength(JSON.stringify(value), "utf8");
function version(value: string): { core: number[]; pre?: string[] } { const match = /^(?:v)?(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?(?:\+[0-9A-Za-z.-]+)?$/u.exec(value); if (!match) return { core: [0, 0, 0] }; return { core: [Number(match[1]), Number(match[2]), Number(match[3])], ...(match[4] === undefined ? {} : { pre: match[4].split(".") }) }; }
function comparePre(left: string[], right: string[]): number { for (let index = 0; index < Math.max(left.length, right.length); index++) { const a = left[index], b = right[index]; if (a === undefined) return -1; if (b === undefined) return 1; if (a === b) continue; const aNumber = /^\d+$/u.test(a), bNumber = /^\d+$/u.test(b); if (aNumber && bNumber) { const normalizedA = a.replace(/^0+(?=\d)/u, ""), normalizedB = b.replace(/^0+(?=\d)/u, ""); return normalizedA.length === normalizedB.length ? (normalizedA > normalizedB ? 1 : -1) : (normalizedA.length > normalizedB.length ? 1 : -1); } if (aNumber !== bNumber) return aNumber ? -1 : 1; return a > b ? 1 : -1; } return 0; }
function greaterVersion(left: string, right: string): boolean { const a = version(left), b = version(right); for (let index = 0; index < 3; index++) { if (a.core[index] !== b.core[index]) return a.core[index]! > b.core[index]!; } if (a.pre === undefined || b.pre === undefined) return a.pre === undefined && b.pre !== undefined; return comparePre(a.pre, b.pre) > 0; }
function redact(value: string): string { if (!/[\\/]/u.test(value) || /:\/\//u.test(value)) return value; let result = value.replace(/[A-Za-z]:[\\/](?:[^\s\\/]+[\\/])*([^\s\\/]+)/gu, "$1"); return result.replace(/(^|\s)\/(?:[^\s/]+\/)*([^\s/]+)/gu, (_match, lead: string, leaf: string) => `${lead}${leaf}`).replace(/(^|\s)(?:[^\s\\/]+[\\/])+([^\s\\/]+)/gu, (_match, lead: string, leaf: string) => `${lead}${leaf}`); }
export function normalizeField(value: unknown, max: number, scope = false): string { if (typeof value !== "string" || value.length === 0) throw new ReflectionError("reflection_invalid_input"); const clean = scope ? value.toLowerCase() : redact(value); if (clean.length > max || prohibited.test(clean) || (scope && !/^[a-z0-9-]+$/u.test(clean))) throw new ReflectionError("reflection_invalid_input"); return clean; }
function shortRef(value: unknown): string { if (typeof value !== "string" || value.length === 0 || value.length > 64 || /[\\/]|\.log\b|(?:log|line|stack\s+trace|diff)\s*[:#]?/iu.test(value) || prohibited.test(value)) throw new ReflectionError("reflection_invalid_input"); return value; }
export function estimateInjectionTokens(text: string): number { return Buffer.byteLength(text, "utf8"); }
function ulid(): string { const alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"; let timestamp = Date.now(), time = ""; for (let i = 0; i < 10; i++) { time = alphabet[timestamp % 32] + time; timestamp = Math.floor(timestamp / 32); } let random = ""; for (const byte of randomBytes(16)) random += alphabet[byte & 31]; return time + random; }
function pathFor(root: string, layer: ReflectionLayer, projectRoot: string, run?: string): string { if (layer === "run" && (typeof run !== "string" || !/^[A-Za-z0-9_-]{1,128}$/u.test(run))) throw new ReflectionError("reflection_invalid_run"); return layer === "global" ? join(root, "global.json") : layer === "project" ? join(root, "projects", `${projectKey(projectRoot)}.json`) : join(root, "runs", `${run!}.json`); }

export class ReflectionStore {
  private readonly warned = new Set<string>(); private readonly now: () => number; private readonly sleep: (ms: number) => Promise<void>; private readonly warn: (code: string) => void; private readonly processAlive: (pid: number) => boolean;
  constructor(private readonly root: string, private readonly projectRoot: string, options: ReflectionStoreOptions = {}) { this.now = options.now ?? Date.now; this.sleep = options.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms))); this.warn = options.warn ?? (() => undefined); this.processAlive = options.processAlive ?? ((pid) => { try { process.kill(pid, 0); return true; } catch { return false; } }); }
  private file(layer: ReflectionLayer, run?: string): string { return pathFor(this.root, layer, this.projectRoot, run); }
  private warning(file: string, code: string): void { const key = `${file}:${code}`; if (!this.warned.has(key)) { this.warned.add(key); this.warn(code); } }
  private async artifacts(file: string, olderThan?: number): Promise<void> { const dir = dirname(file), prefix = `${basename(file)}.`; const names = await readdir(dir).catch(() => []); for (const name of names) { if (!name.startsWith(prefix) || name.startsWith(`${basename(file)}.lock`)) continue; const path = join(dir, name), info = await stat(path).catch(() => undefined); if (olderThan !== undefined && (info === undefined || info.mtimeMs >= olderThan)) continue; await rm(path, { force: true }).catch(() => undefined); } }
  private async temps(file: string): Promise<void> { const dir = dirname(file); for (const name of await readdir(dir).catch(() => [])) if (name.startsWith(`${basename(file)}.`) && name.endsWith(".tmp")) await rm(join(dir, name), { force: true }).catch(() => undefined); }
  private async load(file: string, layer: ReflectionLayer, currentVersion: string | undefined, lock: HeldLock): Promise<{ bucket: ReflectionBucket; future: boolean; legacy: boolean; changed: boolean }> {
    try {
      const parsed = JSON.parse(await readFile(file, "utf8")) as { v?: number; updatedAt?: unknown; entries?: unknown };
      if (parsed.v !== 0 && parsed.v !== 1 && (parsed.v ?? 0) > 1) { this.warning(file, "reflection_future_schema"); return { bucket: EMPTY(), future: true, legacy: false, changed: false }; }
      if (parsed.v !== 0 && parsed.v !== 1 || typeof parsed.updatedAt !== "string" || Number.isNaN(Date.parse(parsed.updatedAt)) || !Array.isArray(parsed.entries)) throw new Error("invalid");
      const bucket = { v: 1 as const, updatedAt: parsed.updatedAt, entries: parsed.entries as ReflectionEntry[] };
      if (!bucket.entries.every((entry) => this.validEntry(entry))) throw new Error("invalid");
      const cutoff = this.now() - ages[layer]; const before = bucket.entries.length;
      bucket.entries = bucket.entries.filter((entry) => Date.parse(entry.lastSeen) >= cutoff && !(currentVersion && entry.status === "promoted" && entry.promotedAtVersion && greaterVersion(currentVersion, entry.promotedAtVersion)));
      return { bucket, future: false, legacy: parsed.v === 0, changed: parsed.v === 0 || before !== bucket.entries.length };
    } catch (error: any) {
      if (error?.code === "ENOENT") return { bucket: EMPTY(), future: false, legacy: false, changed: false };
      await this.withOwnership(lock, async () => { await rename(file, `${file}.corrupt.${this.now()}`); }); this.warning(file, "reflection_corrupt_json"); return { bucket: EMPTY(), future: false, legacy: false, changed: false };
    }
  }
  private validEntry(entry: unknown): entry is ReflectionEntry { if (!entry || typeof entry !== "object" || jsonBytes(entry) > MAX_ENTRY_BYTES) return false; const item = entry as ReflectionEntry; try { normalizeField(item.scope, 80, true); normalizeField(item.trigger, 160); normalizeField(item.cause, 360); normalizeField(item.prevention, 500); shortRef(item.evidenceRef); if (item.status === "promoted") { shortRef(item.promotedRef); if (typeof item.promotedAtVersion !== "string" || !/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/u.test(item.promotedAtVersion)) return false; } return /^[0-9A-HJKMNP-TV-Z]{26}$/u.test(item.id) && evidence.has(item.evidence) && ["active", "promotable", "promoted"].includes(item.status) && Number.isInteger(item.hits) && item.hits > 0 && !Number.isNaN(Date.parse(item.lastSeen)) && !Number.isNaN(Date.parse(item.firstSeen)); } catch { return false; } }
  private owner(token: string): string { return JSON.stringify({ pid: process.pid, token }); }
  private live(raw: string | undefined): boolean { try { const owner = JSON.parse(raw ?? "") as { pid?: unknown; token?: unknown }; if (typeof owner.token !== "string" || typeof owner.pid !== "number" || !Number.isInteger(owner.pid)) return false; return owner.pid === process.pid ? activeTokens.has(owner.token) : this.processAlive(owner.pid); } catch { return false; } }
  private async heartbeat(handle: import("node:fs/promises").FileHandle, owner: string): Promise<void> { await handle.truncate(0); await handle.write(owner, 0, "utf8"); await handle.sync(); }
  private async acquire(path: string): Promise<HeldLock> { const token = randomBytes(24).toString("hex"), owner = this.owner(token); const handle = await open(path, "wx", 0o600); activeTokens.add(token); try { await this.heartbeat(handle, owner); const timer = setInterval(() => { void this.heartbeat(handle, owner).catch(() => undefined); }, 1000); timer.unref(); return { handle, path, token, timer }; } catch (error) { const opened = await handle.stat().catch(() => undefined), removedOpen = await unlink(path).then(() => true).catch(() => false); await handle.close().catch(() => undefined); if (!removedOpen && opened !== undefined) { const current = await stat(path).catch(() => undefined); if (current !== undefined && current.dev === opened.dev && current.ino === opened.ino && Date.now() - current.mtimeMs <= 5000) await unlink(path).catch(() => undefined); } activeTokens.delete(token); throw error; } }
  private async stale(path: string, finiteLease: boolean): Promise<boolean> { const info = await stat(path).catch(() => undefined); if (!info) return false; const age = this.now() - info.mtimeMs; return age > 5000 && ((finiteLease && age > MAX_LEASE_AGE) || !this.live(await readFile(path, "utf8").catch(() => undefined))); }
  private async recoveryClaims(path: string): Promise<string[]> { const prefix = `${basename(path)}.recover.`; const claims = (await readdir(dirname(path)).catch(() => [])).filter((name) => name.startsWith(prefix)).map((name) => join(dirname(path), name)); for (const claim of claims) if (await this.stale(claim, false)) await unlink(claim).catch(() => undefined); return (await readdir(dirname(path)).catch(() => [])).filter((name) => name.startsWith(prefix)).map((name) => join(dirname(path), name)).sort(); }
  private async recoverGuard(path: string): Promise<boolean> { if (!await this.stale(path, false)) return false; const claim = await this.acquire(`${path}.recover.${randomBytes(12).toString("hex")}`); try { const claims = await this.recoveryClaims(path); if (claims[0] !== claim.path || !await this.stale(path, false)) return false; await unlink(path).catch(() => undefined); return true; } finally { await this.releaseGuard(claim); } }
  private async recoverStale(path: string): Promise<boolean> { if (!await this.stale(path, true)) return false; const guard = await this.pathGuard(path); if (!guard) return false; try { if (!await this.stale(path, true)) return false; await unlink(path).catch(() => undefined); return true; } finally { await this.releaseGuard(guard); } }
  async cleanupStaleLocks(): Promise<number> { const paths: string[] = []; for (const directory of [this.root, join(this.root, "runs"), join(this.root, "projects")]) for (const name of await readdir(directory).catch(() => [])) if (/\.json\.lock(?:\.guard)?$/u.test(name)) paths.push(join(directory, name)); paths.sort((left, right) => Number(right.endsWith(".guard")) - Number(left.endsWith(".guard")) || left.localeCompare(right)); let removed = 0; for (const path of paths.slice(0, MAX_STALE_LOCK_CLEANUP)) { try { if (path.endsWith(".guard") ? await this.recoverGuard(path) : await this.recoverStale(path)) removed++; } catch { this.warning(path, "reflection_cleanup_failed"); } } return removed; }
  private async lock(file: string): Promise<HeldLock> { const path = `${file}.lock`; for (let attempt = 0; attempt < 3; attempt++) { try { return await this.acquire(path); } catch (error: any) { if (error?.code !== "EEXIST") throw new ReflectionError("reflection_lock_timeout"); await this.recoverStale(path); await this.sleep(10 * 2 ** attempt); } } throw new ReflectionError("reflection_lock_timeout"); }
  private async pathGuard(path: string): Promise<HeldLock | undefined> { const guard = `${path}.guard`; for (let attempt = 0; attempt < 3; attempt++) { try { if ((await this.recoveryClaims(guard)).length > 0) { await this.sleep(2 ** attempt); continue; } const candidate = await this.acquire(guard); if ((await this.recoveryClaims(guard)).length === 0) return candidate; await this.releaseGuard(candidate); } catch (error: any) { if (error?.code !== "EEXIST") return undefined; await this.recoverGuard(guard); } await this.sleep(2 ** attempt); } return undefined; }
  private async releaseGuard(guard: HeldLock): Promise<void> { clearInterval(guard.timer); await guard.handle.close().catch(() => undefined); try { if (await readFile(guard.path, "utf8").catch(() => undefined) === this.owner(guard.token)) await unlink(guard.path).catch(() => undefined); } finally { activeTokens.delete(guard.token); } }
  private async withOwnership<T>(lock: Pick<HeldLock, "path" | "token">, action: () => Promise<T>): Promise<T> { const guard = await this.pathGuard(lock.path); if (!guard) throw new ReflectionError("reflection_lock_lost"); try { if (await readFile(lock.path, "utf8").catch(() => undefined) !== this.owner(lock.token)) throw new ReflectionError("reflection_lock_lost"); return await action(); } finally { await this.releaseGuard(guard); } }
  private async release(lock: HeldLock): Promise<void> { clearInterval(lock.timer); await lock.handle.close().catch(() => undefined); try { await this.withOwnership(lock, async () => { await unlink(lock.path); }); } catch { /* a newer owner or stale recovery owns the path */ } finally { activeTokens.delete(lock.token); } }
  private async save(file: string, bucket: ReflectionBucket, lock: HeldLock): Promise<void> { if (bucket.entries.some((entry) => jsonBytes(entry) > MAX_ENTRY_BYTES) || jsonBytes(bucket) > 32768) throw new ReflectionError("reflection_size_limit"); const temp = `${file}.${ulid()}.tmp`; const handle = await open(temp, "w", 0o600); try { await handle.writeFile(JSON.stringify(bucket)); await handle.sync(); } finally { await handle.close(); } await chmod(temp, 0o600).catch(() => undefined); try { await this.withOwnership(lock, async () => { await rename(temp, file); }); } catch (error) { await rm(temp, { force: true }); throw error; } const dir = await open(dirname(file), "r").catch(() => undefined); await dir?.sync().catch(() => undefined); await dir?.close().catch(() => undefined); }
  async read(layer: ReflectionLayer, run?: string, currentVersion?: string): Promise<ReflectionBucket> { const file = this.file(layer, run); if (!await stat(dirname(file)).catch(() => undefined)) return EMPTY(); const lock = await this.lock(file); try { await this.withOwnership(lock, async () => { await this.temps(file); await this.artifacts(file, this.now() - ages[layer]); }); const loaded = await this.load(file, layer, currentVersion, lock); if (loaded.future) return loaded.bucket; if (loaded.changed) { if (loaded.legacy) await this.withOwnership(lock, async () => { await copyFile(file, `${file}.v0.bak`); }); await this.save(file, loaded.bucket, lock); } return loaded.bucket; } finally { await this.release(lock); } }
  private async transaction<T>(layer: ReflectionLayer, run: string | undefined, currentVersion: string | undefined, fn: (state: ReflectionBucket, file: string, lock: HeldLock) => Promise<T>): Promise<T> { const file = this.file(layer, run); await mkdir(dirname(file), { recursive: true, mode: 0o700 }); await chmod(dirname(file), 0o700).catch(() => undefined); const lock = await this.lock(file); try { const loaded = await this.load(file, layer, currentVersion, lock); if (loaded.future) throw new ReflectionError("reflection_future_schema"); if (loaded.legacy) await this.withOwnership(lock, async () => { await copyFile(file, `${file}.v0.bak`); }); const result = await fn(loaded.bucket, file, lock); await this.save(file, loaded.bucket, lock); return result; } finally { await this.release(lock); } }
  async record(layer: ReflectionLayer, run: string | undefined, input: Record<string, unknown>, currentVersion: string): Promise<ReflectionEntry> { if (!evidence.has(input.evidence as Evidence)) throw new ReflectionError("reflection_invalid_evidence"); const now = new Date(this.now()).toISOString(); const entry: ReflectionEntry = { id: ulid(), scope: normalizeField(input.scope, 80, true), trigger: normalizeField(input.trigger, 160), cause: normalizeField(input.cause, 360), prevention: normalizeField(input.prevention, 500), evidence: input.evidence as Evidence, evidenceRef: shortRef(input.evidenceRef), hits: 1, firstSeen: now, lastSeen: now, status: input.evidence === "user-correction" ? "promotable" : "active" }; if (jsonBytes(entry) > MAX_ENTRY_BYTES) throw new ReflectionError("reflection_size_limit"); return this.transaction(layer, run, currentVersion, async (bucket) => { const same = bucket.entries.find((item) => item.scope === entry.scope); if (same) { same.trigger = entry.trigger; same.hits++; same.lastSeen = now; if (entry.evidence === "user-correction") { same.evidence = entry.evidence; same.evidenceRef = entry.evidenceRef; } same.status = same.hits >= 2 || same.evidence === "user-correction" ? "promotable" : same.status; bucket.updatedAt = now; return same; } bucket.entries.push(entry); while (bucket.entries.length > caps[layer]) bucket.entries.sort((a, b) => a.hits - b.hits || a.lastSeen.localeCompare(b.lastSeen) || a.id.localeCompare(b.id)).shift(); bucket.updatedAt = now; return entry; }); }
  async list(layer: ReflectionLayer, run: string | undefined, currentVersion: string): Promise<ReflectionBucket> { return await this.read(layer, run, currentVersion); }
  async replace(layer: ReflectionLayer, run: string | undefined, id: unknown, input: Record<string, unknown>, currentVersion: string): Promise<ReflectionEntry> { if (typeof id !== "string" || id.length === 0) throw new ReflectionError("reflection_invalid_input"); const now = new Date(this.now()).toISOString(); const replacement = { scope: normalizeField(input.scope, 80, true), trigger: normalizeField(input.trigger, 160), cause: normalizeField(input.cause, 360), prevention: normalizeField(input.prevention, 500) }; return this.transaction(layer, run, currentVersion, async (bucket) => { const entry = bucket.entries.find((item) => item.id === id); if (!entry) throw new ReflectionError("reflection_not_found"); if (bucket.entries.some((item) => item.id !== id && item.scope === replacement.scope)) throw new ReflectionError("reflection_invalid_input"); Object.assign(entry, replacement, { hits: entry.hits + 1, lastSeen: now }); if (entry.hits >= 2 || entry.evidence === "user-correction") entry.status = "promotable"; if (jsonBytes(entry) > MAX_ENTRY_BYTES) throw new ReflectionError("reflection_size_limit"); bucket.updatedAt = now; return entry; }); }
  async forget(layer: ReflectionLayer, run: string | undefined, id: unknown, currentVersion: string): Promise<string> { if (typeof id !== "string" || id.length === 0) throw new ReflectionError("reflection_invalid_input"); return this.transaction(layer, run, currentVersion, async (bucket) => { const index = bucket.entries.findIndex((item) => item.id === id); if (index < 0) return "not-found"; bucket.entries.splice(index, 1); bucket.updatedAt = new Date(this.now()).toISOString(); return "forgotten"; }); }
  async promote(layer: ReflectionLayer, run: string | undefined, id: string, ref: string, currentVersion: string): Promise<string> { return this.transaction(layer, run, currentVersion, async (bucket) => { const entry = bucket.entries.find((item) => item.id === id); if (!entry) throw new ReflectionError("reflection_not_found"); if (entry.status !== "promotable") throw new ReflectionError("reflection_not_promotable"); entry.status = "promoted"; entry.promotedRef = shortRef(ref); entry.promotedAtVersion = currentVersion; bucket.updatedAt = new Date(this.now()).toISOString(); return "promoted"; }); }
  async clear(layer: ReflectionLayer, run: string | undefined, confirmation: string, currentVersion: string): Promise<string> { if ((layer !== "run") && confirmation !== "CLEAR_REFLECTIONS") throw new ReflectionError("reflection_confirmation_required"); return this.transaction(layer, run, currentVersion, async (bucket, file, lock) => { bucket.entries = []; bucket.updatedAt = new Date(this.now()).toISOString(); await this.withOwnership(lock, async () => { await this.artifacts(file); }); return "cleared"; }); }
  async deleteRun(run: string): Promise<void> { const file = this.file("run", run); if (!await stat(dirname(file)).catch(() => undefined)) return; const lock = await this.lock(file); try { await this.withOwnership(lock, async () => { await this.artifacts(file); await rm(file, { force: true }); }); } finally { await this.release(lock); } }
  async inject(layer: ReflectionLayer, run: string | undefined, max: number, tokenBudget: number, currentVersion: string): Promise<string> { return this.injectBuckets([{ layer, run }], max, tokenBudget, currentVersion); }
  async injectBuckets(buckets: readonly { layer: ReflectionLayer; run?: string }[], max: number, tokenBudget: number, currentVersion?: string): Promise<string> { const byScope = new Map<string, ReflectionEntry>(); for (const { layer, run } of buckets) for (const entry of (await this.read(layer, run, currentVersion)).entries) if (!byScope.has(entry.scope)) byScope.set(entry.scope, entry); const entries = [...byScope.values()].sort((a, b) => b.hits - a.hits || a.lastSeen.localeCompare(b.lastSeen) || a.id.localeCompare(b.id)); const lines: string[] = []; for (const entry of entries) { const line = `- [${entry.id}] ${entry.scope} (hits=${entry.hits}): ${entry.prevention}`; if (lines.length >= max || estimateInjectionTokens([...lines, line].join("\n")) > tokenBudget) break; lines.push(line); } return lines.join("\n"); }
}
